# Generated by Django 4.1.10 on 2023-07-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Updat',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
